# Site settings
title: PresskitHero Blog
header-img: img/home-bg-2.jpg
email: hello@presskithero.com
description: "Official blog of PresskitHero.com"
baseurl: ""
url: "http://blog.presskithero.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
